from pygame import USEREVENT

BULLET_EVENT = USEREVENT + 1
GRUNT_FIRE = USEREVENT + 2
FLOODER_FIRE = USEREVENT + 3
SPAWN_GRUNT_RIGHT = USEREVENT + 4
SPAWN_GRUNT_LEFT = USEREVENT + 5
SPAWN_CENTER_FLOODER = USEREVENT + 6
SPAWN_LEFT_FLOODER = USEREVENT + 7
SPAWN_RIGHT_FLOODER = USEREVENT + 8
FIRE_HOMING_BULLET = USEREVENT + 9
SPAWN_PICKUP = USEREVENT + 10
END_OF_POWERUP = USEREVENT + 11
